### ISSUE TITLE
Leg reposition doesnt always use the correct offsets

### ISSUE THREAD

**Issue by BGuven** [rfunduk/jquery-tourbus#26]
Found an issue where offsets of tooltips were off when the legs were getting repositioned with the .reposition() call. 

Issue is caused by having the same class signature for elements in the page. For example:

```
<div class='container'>
  <div class='elements active'>
    <div class='elem-one'></div>
  </div>
  <div class='elements'>
    <div class='elem-one'></div>
  </div>
</div>
```

The selector used for this is : ```data-el=".container .elements.active elem-one"```.  The Leg code instead of using the ```date-el``` selector on reposition calls uses the randomly matching instance of 'elem-one' to read the offset information. 

the line at https://github.com/rfunduk/jquery-tourbus/blob/e9a98c3f32b5a5c2ea7bad63516c2a152661bdb9/src/modules/leg.coffee#L107

should read the offset off of the target selector like: 

```
@targetOffset = $(@$target.selector).offset()
```

**Comment by rfunduk** [comment]
Hm but `@target` should already be the correct element. Can you provide an example that shows this problem (jsfiddle or similar)?

**Comment by BGuven** [comment]
Thanks for getting back to me so soon. Here is the codepen and the steps to reproduce it:

http://codepen.io/anon/pen/XNVeEx

Steps:
1) Tour should start by default
2) hit 'next' button on the tour tooltip
3) Click 'Change Active Row' button which will effectively alter the state of the DOM elements by setting the second row of divs as active.
4) Hit 'reposition' button. (Now this step should re-calculate the offsets, and I think it only would make sense for it to use the selectors we have given it to find its offsets from.)

As you can see from the demo, it tour steps stay on the first row. Is that what you would expect?

**Comment by rfunduk** [comment]
Ah, so yea did you test your change above? It seems to me the problem is that you're trying to change the elements in the tour dynamically. That's not something I had in mind. Even if we calculate the offsets by re-selecting using the selector provided on init, when you go to the next step that leg's element (and indeed even the one we re-positioned) will be the _old_ element still.

I'm not sure exactly how I would approach this since I'm not sure of the real use-case from this demo... if there's a static and small # of rows I might just make multiple tours and control which step gets shown based on what step they are already on at the time of the switch (eg, stop current tour, start one for other row at same index). If it was a table of dynamic data then... not entirely sure but you could maybe go down a level and actually construct tour legs and replace them in the `Bus` instance or something like that.

**Comment by rfunduk** [comment]
Specifically, I'm talking about this:

https://github.com/rfunduk/jquery-tourbus/blob/e9a98c3f32b5a5c2ea7bad63516c2a152661bdb9/src/modules/leg.coffee#L10

The `@target` of the `Leg` itself will still be the old target, which seems like a recipe for confusion and weird bugs later. I guess thinking about it for a few more minutes, I think maybe just the make-new-leg-and-replace-in-tour is the best way to approach this.

I would do that by using the `expose` feature to get the `Bus` class, and add a method to it (like `replaceLeg`. Then you can, on row switch, replace _all_ of the legs with ones for the new target row.

**Comment by rfunduk** [comment]
On second thought, there's a much easier way to do this. Your reposition handler becomes:

```js
var leg = tour.currentLeg()
leg.$target = $(leg.$original.data('el'))
leg.reposition()
```

This does suffer from the problem I mentioned above in that when you click 'next', it will go back to the original row because only that one leg was updated. So, in your window load handler:

```js
$.tourbus('expose', this)
tourbus.Bus.prototype.updateLegTargets = function() {
  $.each( this.legs, function( i, leg ) {
    leg.$target = $(leg.$original.data('el'))
    leg.reposition()
  } )
}
```

And then your reposition handler is just:

```
tour.updateLegTargets()
```

Here's the updated codepen: http://codepen.io/rfunduk/pen/GNyQNg?editors=0010
